-- Auth identities are intentionally not inserted with SQL. Create the initial
-- Admin through Supabase Auth, then follow docs/supabase-phase3-test-accounts.md.
-- All later Student and Teacher test identities should be invited through the
-- Admin Users UI so the production provisioning path is exercised.
